### ISSUE TITLE
Path of the game engine with Steam

### ISSUE THREAD

**Issue by JafiMapping** [eGax/TrenchBroom_xtras_plus#4]
What is the path of the game engine with Steam again?

I've lost it when instalating the new .CFG... 
 
I dont' remember the trick,  and I know that the quake2re.exe does'nt work 

Maybe put it on your install instructions for the next newbie :) 

TY

**Comment by eGax** [comment]
I cover that in the basic [setup directions](https://github.com/eGax/TrenchBroom_xtras_plus/tree/main/games_wip/Quake2RE#setup)

It is very dependent on where you have your SteamLibrary set to. By default its usually `~/.local/share/Steam/steamapps/common/Quake 2/rerelease/`

On windows it is probably inside `C:\Program Files (x86)\Steam\` be default.
